http_port: 8080
http_target_url: https://jsonplaceholder.typicode.com
target_routes:
  - path_prefix: /todos/*
    target_url: https://jsonplaceholder.typicode.com
  - path_prefix: /api/v1/products/
    target_url: https://api.escuelajs.co
  - path_prefix: /api/v1/users/
    target_url: https://api.escuelajs.co
  - path_prefix: /api/v1/users/is-available
    target_url: https://api.escuelajs.co
sqlite_db_path: traffic_inspector.db
recording_mode: false
replay_mode: false
tls:
  enabled: false
  cert_file: ./certs/server.crt
  key_file: ./certs/server.key
  port: 8443
  allow_insecure: false
api_validation:
  enabled: true
  spec_path: "/path/to/openapi.yaml"
  validate_requests: true
  validate_responses: true
  strict_mode: false
  continue_on_validation: false