name: 🚀 Feature Request
description: I have a suggestion (and may want to implement it 🙂)!
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to help us understand your feature request better.
  - type: textarea
    id: description
    attributes:
      label: Describe the feature you'd like
      placeholder: I'd like this feature to...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      placeholder: I've considered...
    validations:
      required: false
  - type: checkboxes
    id: checks
    attributes:
      label: Extra fields
      options:
        - label: I have used the search function to check if a similar feature request already exists
          required: true
        - label: I'd like to work on this feature request
  - type: markdown
    attributes:
      value: |
        Thanks for submitting this feature request! We will review it and get back to you as soon as possible.