name: AI workflow

on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'How can i help you?'
        # Default value if no value is explicitly provided
        default: 'Hello Gemini!'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
        type: string

env:
  API_KEY: ${{ secrets.API_KEY }}
jobs:
  # This workflow contains a single job called "greet"
  ai:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
  
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Ask Me
        run: go run ./cmd/main.go ${{ inputs.name }}

